name: bible_plus
version: 0.1.3
description: Library for reading PDB bible files.
homepage: https://github.com/StaymanHou/bible_plus_dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.14.2
